version: '3'
services:
  dashboard:
    container_name: patchwork-dashboard
    build: .
    restart: always
    env_file: .env
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    ports:
      - '3001:3000'

networks:
  external_network:
  internal_network:
    internal: true
