development:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_development_default
    - dashboard_development_ban_status
    - dashboard_development_scheduler
  :scheduler:
    :schedule:
      FetchContentKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchContentKeywordScheduler
        queue: dashboard_development_scheduler
      FetchSpamKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchSpamKeywordScheduler
        queue: dashboard_development_scheduler
      FollowBlueskyBotScheduler:
        every: '10m'
        class: Scheduler::FollowBlueskyBotScheduler
        queue: dashboard_development_scheduler

staging:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_staging_default
    - dashboard_staging_ban_status
    - dashboard_staging_scheduler
  :scheduler:
    :schedule:
      FetchContentKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchContentKeywordScheduler
        queue: dashboard_staging_scheduler
      FetchSpamKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchSpamKeywordScheduler
        queue: dashboard_staging_scheduler
      FollowBlueskyBotScheduler:
        every: '10m'
        class: Scheduler::FollowBlueskyBotScheduler
        queue: dashboard_staging_scheduler

production:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_production_default
    - dashboard_production_ban_status
    - dashboard_production_scheduler
  :scheduler:
    :schedule:
      FetchContentKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchContentKeywordScheduler
        queue: dashboard_production_scheduler
      FetchSpamKeywordScheduler:
        every: '5m'
        class: Scheduler::FetchSpamKeywordScheduler
        queue: dashboard_production_scheduler
      FollowBlueskyBotScheduler:
        every: '10m'
        class: Scheduler::FollowBlueskyBotScheduler
        queue: dashboard_production_scheduler
