development:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_development_default
    - dashboard_development_ban_status
    - dashboard_development_scheduler
  :scheduler:
    :schedule:
      FetchContentKeywordScheduler:
        every: '1m'
        class: FetchContentKeywordScheduler
        queue: dashboard_development_scheduler

staging:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_staging_default
    - dashboard_staging_ban_status

production:
  :verbose: true
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 10 } %>
  :queues:
    - dashboard_production_default
    - dashboard_production_ban_status
